#pragma once

#include "gvCmdMgr.h"

GV_COMMAND(GVHelpCmd,      GV_CMD_TYPE_COMMON);
GV_COMMAND(GVQuitCmd,      GV_CMD_TYPE_COMMON);
GV_COMMAND(GVHistoryCmd,   GV_CMD_TYPE_COMMON);
GV_COMMAND(GVDofileCmd,    GV_CMD_TYPE_COMMON);
GV_COMMAND(GVUsageCmd,     GV_CMD_TYPE_COMMON);
GV_COMMAND(GVLogFileCmd,   GV_CMD_TYPE_COMMON);


