
// Generated by Cadence Genus(TM) Synthesis Solution 19.20-d227_1
// Generated on: Jun 16 2021 18:28:22 PDT (Jun 17 2021 01:28:22 UTC)

// Verification Directory fv/top 

module top(clk, ena, rst, Tsync, Tgdel, Tgate, Tlen, Sync, Gate, Done,
     prev_state, prev_cnt, prev_cnt_len);
  input clk, ena, rst;
  input [7:0] Tsync, Tgdel;
  input [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  input [4:0] prev_state;
  output Sync, Gate, Done;
  wire clk, ena, rst;
  wire [7:0] Tsync, Tgdel;
  wire [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  wire [4:0] prev_state;
  wire Sync, Gate, Done;
  wire n_51, n_279, n_292, n_293, n_330, n_331, n_332, n_333;
  wire n_334, n_335, n_336, n_337, n_384, n_385, n_386, n_387;
  wire n_388, n_389, n_390, n_391, n_392, n_393, n_394, n_395;
  wire n_396, n_397, n_398, n_399, n_400, n_401, n_408, n_409;
  wire n_410, n_411, n_413, n_414, n_415, n_416, n_417, n_418;
  wire n_419, n_420;
  or g426 (n_420, n_419, n_332);
  or g427 (n_419, n_418, n_330);
  or g428 (n_418, n_417, n_334);
  or g429 (n_417, n_416, n_337);
  nand g430 (Sync, n_51, n_410);
  or g431 (n_416, n_415, n_331);
  or g432 (n_51, n_401, prev_state[0]);
  not g433 (Done, n_51);
  or g434 (n_415, n_414, n_336);
  or g435 (n_401, n_400, prev_state[2]);
  or g436 (n_400, n_399, wc);
  not gc (wc, prev_state[4]);
  or g437 (n_414, n_413, n_333);
  or g438 (n_413, n_411, prev_state[0]);
  or g439 (n_410, n_409, wc0);
  not gc0 (wc0, prev_state[0]);
  or g440 (n_399, n_398, n_279);
  or g441 (n_398, n_396, n_397);
  or g442 (n_409, n_408, prev_state[2]);
  or g443 (n_411, wc1, n_408);
  not gc1 (wc1, prev_state[2]);
  or g444 (n_408, n_279, prev_state[4]);
  or g445 (n_397, n_394, n_395);
  or g446 (n_396, n_392, n_393);
  or g447 (n_279, n_292, n_293);
  or g448 (n_395, n_390, n_391);
  or g449 (n_394, n_388, n_389);
  or g450 (n_393, n_386, n_387);
  or g451 (n_392, n_384, n_385);
  or g452 (n_292, wc2, rst);
  not gc2 (wc2, ena);
  or g453 (n_293, prev_state[3], prev_state[1]);
  or g454 (n_391, prev_cnt_len[1], prev_cnt_len[0]);
  or g455 (n_390, prev_cnt_len[3], prev_cnt_len[2]);
  or g456 (n_389, prev_cnt_len[5], prev_cnt_len[4]);
  or g457 (n_388, prev_cnt_len[7], prev_cnt_len[6]);
  or g458 (n_387, prev_cnt_len[9], prev_cnt_len[8]);
  or g459 (n_386, prev_cnt_len[11], prev_cnt_len[10]);
  or g460 (n_330, prev_cnt[15], prev_cnt[14]);
  or g461 (n_384, prev_cnt_len[15], prev_cnt_len[14]);
  or g462 (n_337, prev_cnt[1], prev_cnt[0]);
  or g463 (n_336, prev_cnt[3], prev_cnt[2]);
  or g464 (n_335, prev_cnt[5], prev_cnt[4]);
  or g465 (n_334, prev_cnt[7], prev_cnt[6]);
  or g466 (n_333, prev_cnt[9], prev_cnt[8]);
  or g467 (n_332, prev_cnt[11], prev_cnt[10]);
  or g468 (n_331, prev_cnt[13], prev_cnt[12]);
  or g469 (n_385, prev_cnt_len[13], prev_cnt_len[12]);
  nor g470 (Gate, n_420, n_335);
endmodule

