
// Generated by Cadence Genus(TM) Synthesis Solution 19.20-d227_1
// Generated on: Jun 16 2021 18:29:26 PDT (Jun 17 2021 01:29:26 UTC)

// Verification Directory fv/top 

module top(clk, ena, rst, Tsync, Tgdel, Tgate, Tlen, Sync, Gate, Done,
     prev_state, prev_cnt, prev_cnt_len);
  input clk, ena, rst;
  input [7:0] Tsync, Tgdel;
  input [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  input [4:0] prev_state;
  output Sync, Gate, Done;
  wire clk, ena, rst;
  wire [7:0] Tsync, Tgdel;
  wire [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  wire [4:0] prev_state;
  wire Sync, Gate, Done;
  wire n_78, n_79, n_80, n_81, n_82;
  assign Done = 1'b0;
  assign Gate = 1'b0;
  or g72 (n_81, wc, n_78);
  not gc (wc, prev_state[0]);
  or g73 (n_82, n_79, n_80);
  or g74 (n_80, prev_state[2], prev_state[1]);
  or g75 (n_79, prev_state[4], prev_state[3]);
  or g76 (n_78, wc0, rst);
  not gc0 (wc0, ena);
  nor g77 (Sync, n_81, n_82);
endmodule

