#pragma once

#include "gvCmdMgr.h"

GV_COMMAND(GVRandomSetSafe, GV_CMD_TYPE_SIMULATE);
GV_COMMAND(SetVSim, GV_CMD_TYPE_SIMULATE);
GV_COMMAND(VSimulate, GV_CMD_TYPE_SIMULATE);
GV_COMMAND(VCDPrint, GV_CMD_TYPE_SIMULATE);
