
// Generated by Cadence Genus(TM) Synthesis Solution 19.20-d227_1
// Generated on: Aug  3 2021 03:02:40 PDT (Aug  3 2021 10:02:40 UTC)

// Verification Directory fv/top 

module top(clk, ena, rst, Tsync, Tgdel, Tgate, Tlen, Sync, Gate, Done,
     prev_state, prev_cnt, prev_cnt_len, cnt, state);
  input clk, ena, rst;
  input [7:0] Tsync, Tgdel;
  input [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  input [4:0] prev_state;
  output Sync, Gate, Done;
  output [15:0] cnt;
  output [4:0] state;
  wire clk, ena, rst;
  wire [7:0] Tsync, Tgdel;
  wire [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  wire [4:0] prev_state;
  wire Sync, Gate, Done;
  wire [15:0] cnt;
  wire [4:0] state;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41;
  assign state[2] = 1'b0;
  assign state[3] = 1'b0;
  assign state[4] = 1'b0;
  assign Done = 1'b0;
  assign Gate = 1'b0;
  nand g1850 (n_41, n_21, n_33);
  nand g1848 (n_40, n_20, n_18);
  nand g1849 (n_39, n_29, n_24);
  nand g1853 (n_38, n_25, n_19);
  nand g1854 (n_37, n_27, n_26);
  nand g1851 (n_36, n_17, n_16);
  nand g1852 (n_35, n_31, n_23);
  nand g1847 (n_34, n_22, n_30);
  nand g1868 (n_33, Tsync[5], n_32);
  nand g1867 (n_31, prev_cnt[3], n_28);
  nand g1860 (n_30, Tsync[0], n_32);
  nand g1858 (n_29, prev_cnt[7], n_28);
  nand g1856 (n_27, prev_cnt[1], n_28);
  nand g1857 (n_26, Tsync[1], n_32);
  nand g1870 (n_25, prev_cnt[4], n_28);
  nand g1862 (n_24, Tsync[7], n_32);
  nand g1875 (n_23, Tsync[3], n_32);
  nand g1859 (n_22, prev_cnt[0], n_28);
  nand g1873 (n_21, prev_cnt[5], n_28);
  nand g1863 (n_20, prev_cnt[6], n_28);
  nand g1871 (n_19, Tsync[4], n_32);
  nand g1865 (n_18, Tsync[6], n_32);
  nand g1876 (n_17, prev_cnt[2], n_28);
  nand g1877 (n_16, Tsync[2], n_32);
  and g1864 (n_15, ena, prev_cnt[13], n_12, n_13);
  and g1855 (n_14, ena, prev_cnt[14], n_12, n_13);
  and g1861 (n_11, ena, prev_cnt[15], n_12, n_13);
  and g1866 (n_10, ena, prev_cnt[12], n_12, n_13);
  and g1874 (n_9, ena, prev_cnt[9], n_12, n_13);
  and g1869 (n_8, ena, prev_cnt[10], n_12, n_13);
  and g1872 (n_7, ena, prev_cnt[11], n_12, n_13);
  and g1878 (n_6, ena, prev_cnt[8], n_12, n_13);
  not g1880 (n_5, n_3);
  and g1879 (n_28, ena, n_12, n_13);
  assign state[0] = n_3;
  not g1882 (n_32, n_3);
  nand g1883 (n_3, ena, n_12, n_2);
  not g1884 (n_13, n_2);
  nor g1885 (n_2, prev_state[1], prev_state[2], n_1);
  nand g1886 (n_1, prev_state[0], n_0);
  nor g1887 (n_0, prev_state[3], prev_state[4]);
  not g1888 (n_12, rst);
  assign Sync = n_32;
  assign cnt[8] = n_6;
  assign cnt[15] = n_11;
  assign cnt[14] = n_14;
  assign cnt[11] = n_7;
  assign cnt[13] = n_15;
  assign cnt[10] = n_8;
  assign cnt[9] = n_9;
  assign cnt[12] = n_10;
  assign cnt[2] = n_36;
  assign cnt[7] = n_39;
  assign cnt[5] = n_41;
  assign cnt[6] = n_40;
  assign cnt[3] = n_35;
  assign cnt[4] = n_38;
  assign cnt[1] = n_37;
  assign cnt[0] = n_34;
  assign state[1] = n_5;
endmodule

