
// Generated by Cadence Genus(TM) Synthesis Solution 19.20-d227_1
// Generated on: Jun 16 2021 06:16:17 PDT (Jun 16 2021 13:16:17 UTC)

// Verification Directory fv/top 

module top(clk, ena, rst, Tsync, Tgdel, Tgate, Tlen, Sync, Gate, Done,
     prev_state, prev_cnt, prev_cnt_len);
  input clk, ena, rst;
  input [7:0] Tsync, Tgdel;
  input [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  input [4:0] prev_state;
  output Sync, Gate, Done;
  wire clk, ena, rst;
  wire [7:0] Tsync, Tgdel;
  wire [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  wire [4:0] prev_state;
  wire Sync, Gate, Done;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25;
  and g1891 (n_25, n_4, n_3, n_2, n_24);
  nor g1892 (n_24, prev_cnt[14], prev_cnt[15], n_23);
  nand g1894 (n_23, n_7, n_5, n_6, n_21);
  nand g1893 (n_22, n_18, n_19);
  nor g1898 (n_21, prev_state[0], prev_cnt[8], prev_cnt[9], n_17);
  not g1895 (n_20, n_19);
  or g1896 (n_19, prev_state[2], prev_state[0], n_15);
  nand g1899 (n_18, prev_state[0], n_0, n_16);
  nand g1900 (n_17, prev_state[2], n_16);
  nand g1897 (n_15, prev_state[4], n_12, n_14);
  nor g1902 (n_16, prev_state[4], n_13);
  and g1901 (n_14, n_11, n_9, n_10, n_8);
  not g1903 (n_13, n_12);
  nor g1905 (n_12, prev_state[1], prev_state[3], rst, n_1);
  nor g1906 (n_11, prev_cnt_len[12], prev_cnt_len[13],
       prev_cnt_len[14], prev_cnt_len[15]);
  nor g1907 (n_10, prev_cnt_len[0], prev_cnt_len[1], prev_cnt_len[2],
       prev_cnt_len[3]);
  nor g1908 (n_9, prev_cnt_len[8], prev_cnt_len[9], prev_cnt_len[10],
       prev_cnt_len[11]);
  nor g1904 (n_8, prev_cnt_len[4], prev_cnt_len[5], prev_cnt_len[6],
       prev_cnt_len[7]);
  nor g1909 (n_7, prev_cnt[0], prev_cnt[1]);
  nor g1910 (n_6, prev_cnt[12], prev_cnt[13]);
  nor g1911 (n_5, prev_cnt[6], prev_cnt[7]);
  nor g1912 (n_4, prev_cnt[4], prev_cnt[5]);
  nor g1913 (n_3, prev_cnt[10], prev_cnt[11]);
  nor g1914 (n_2, prev_cnt[2], prev_cnt[3]);
  not g1915 (n_1, ena);
  not g1916 (n_0, prev_state[2]);
  assign Gate = n_25;
  assign Sync = n_22;
  assign Done = n_20;
endmodule

