
// Generated by Cadence Genus(TM) Synthesis Solution 19.20-d227_1
// Generated on: Jun 16 2021 06:17:54 PDT (Jun 16 2021 13:17:54 UTC)

// Verification Directory fv/top 

module top(clk, ena, rst, Tsync, Tgdel, Tgate, Tlen, Sync, Gate, Done,
     prev_state, prev_cnt, prev_cnt_len);
  input clk, ena, rst;
  input [7:0] Tsync, Tgdel;
  input [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  input [4:0] prev_state;
  output Sync, Gate, Done;
  wire clk, ena, rst;
  wire [7:0] Tsync, Tgdel;
  wire [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  wire [4:0] prev_state;
  wire Sync, Gate, Done;
  wire n_39, n_101, n_134, n_135, n_138, n_148, n_149, n_154;
  wire n_155, n_162, n_163, n_164, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_193, n_194, n_199, n_200;
  assign Gate = 1'b0;
  nand g253 (Sync, n_39, n_200);
  or g254 (n_39, n_194, prev_state[0]);
  not g255 (Done, n_39);
  or g256 (n_194, n_193, wc);
  not gc (wc, prev_state[4]);
  or g257 (n_193, n_101, n_138);
  or g258 (n_101, n_187, n_188);
  or g259 (n_200, n_199, wc0);
  not gc0 (wc0, prev_state[0]);
  or g260 (n_188, n_185, n_186);
  or g261 (n_186, n_181, n_182);
  or g262 (n_199, n_138, prev_state[4]);
  or g263 (n_181, n_134, n_135);
  or g264 (n_138, n_163, n_164);
  or g265 (n_187, n_183, n_184);
  or g266 (n_164, prev_state[1], n_162);
  or g267 (n_135, n_154, n_155);
  or g268 (n_134, n_148, n_149);
  or g269 (n_182, prev_cnt_len[15], prev_cnt_len[14]);
  or g270 (n_148, prev_cnt_len[5], prev_cnt_len[4]);
  or g271 (n_163, prev_state[3], prev_state[2]);
  or g272 (n_162, wc1, rst);
  not gc1 (wc1, ena);
  or g273 (n_184, prev_cnt_len[3], prev_cnt_len[2]);
  or g274 (n_155, prev_cnt_len[11], prev_cnt_len[10]);
  or g275 (n_154, prev_cnt_len[9], prev_cnt_len[8]);
  or g276 (n_185, prev_cnt_len[1], prev_cnt_len[0]);
  or g277 (n_149, prev_cnt_len[7], prev_cnt_len[6]);
  or g278 (n_183, prev_cnt_len[13], prev_cnt_len[12]);
endmodule

